# This rule is not used by the project database-backup-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over db.dev-ai.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: database-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasebackup-admin-role
rules:
- apiGroups:
  - db.dev-ai.io
  resources:
  - databasebackups
  verbs:
  - '*'
- apiGroups:
  - db.dev-ai.io
  resources:
  - databasebackups/status
  verbs:
  - get
